name: update-flake-inputs

on:
  schedule:
    - cron: "17 * * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-flake-inputs-latest
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update flake inputs
        id: flake
        uses: Drazape/commit-flake-inputs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: alpha
          commit_message: "chore(flake): ops: update inputs"
          flake_directory: "."
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_name: "Drazape"
          git_user_email: "Drazape@outlook.com"

      - name: Show result
        run: |
          echo "changed: ${{ steps.flake.outputs.changed }}"
          echo "commit: ${{ steps.flake.outputs.commit_sha }}"
